
import java.awt.event.WindowEvent;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class InputForm extends javax.swing.JFrame {

    /**
     * Creates new form InputForm
     */
    //String reg, lar;
    String category;
    CourseWork1 coursework;

    public InputForm(CourseWork1 cw) {
        initComponents();
        coursework = cw;
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonReglar = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        addItems = new javax.swing.JLabel();
        inputSeperator = new javax.swing.JSeparator();
        inputNo = new javax.swing.JLabel();
        itemNoField = new javax.swing.JTextField();
        inputName = new javax.swing.JLabel();
        itemNameField = new javax.swing.JTextField();
        inputCategory = new javax.swing.JLabel();
        itemCategory = new javax.swing.JComboBox();
        inputSize = new javax.swing.JLabel();
        radioRegular = new javax.swing.JRadioButton();
        radioLarge = new javax.swing.JRadioButton();
        inputPricePiece = new javax.swing.JLabel();
        itemPricePiece = new javax.swing.JTextField();
        inputPriceKilos = new javax.swing.JLabel();
        itemPriceKg = new javax.swing.JTextField();
        inputAdd = new javax.swing.JButton();
        menuLine = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        open = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD DETAILS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        addItems.setFont(new java.awt.Font("Raleway", 0, 36)); // NOI18N
        addItems.setText("ADD ITEMS");

        inputSeperator.setBackground(new java.awt.Color(0, 0, 0));

        inputNo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        inputNo.setText("Item No:");

        itemNoField.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        itemNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNoFieldActionPerformed(evt);
            }
        });

        inputName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        inputName.setText("Item Name:");

        itemNameField.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N

        inputCategory.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        inputCategory.setText("Category:");

        itemCategory.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        itemCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a Category", "Lakhamari", "Milk Products", "Ladoo", "Salty", "Plain" }));

        inputSize.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        inputSize.setText("Size:");

        radioRegular.setBackground(new java.awt.Color(153, 204, 255));
        buttonReglar.add(radioRegular);
        radioRegular.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        radioRegular.setText("Regular");

        radioLarge.setBackground(new java.awt.Color(153, 204, 255));
        buttonReglar.add(radioLarge);
        radioLarge.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        radioLarge.setText("Large");

        inputPricePiece.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        inputPricePiece.setText("Price (Piece):");

        itemPricePiece.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N

        inputPriceKilos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        inputPriceKilos.setText("Price (Kg):");

        itemPriceKg.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N

        inputAdd.setBackground(new java.awt.Color(153, 204, 255));
        inputAdd.setFont(new java.awt.Font("Raleway", 0, 30)); // NOI18N
        inputAdd.setText("ADD");
        inputAdd.setBorder(null);
        inputAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(inputPriceKilos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPricePiece, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputSize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputCategory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radioRegular, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(radioLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(itemPricePiece, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemPriceKg, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(itemNoField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(addItems)
                        .addGap(237, 237, 237))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(inputAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(inputSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(addItems, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputNo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioRegular, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addComponent(radioLarge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPricePiece, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemPricePiece, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPriceKilos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemPriceKg, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(86, 86, 86))
        );

        menuLine.setBackground(new java.awt.Color(0, 0, 0));

        jMenu1.setText("File");

        open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/envelope.png"))); // NOI18N
        open.setText("Open");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        jMenu1.add(open);
        jMenu1.add(jSeparator1);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        menuLine.add(jMenu1);

        setJMenuBar(menuLine);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNoFieldActionPerformed

    private void inputAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAddActionPerformed
        /*Initillizaing and declaring the String in the same time*/
        String itemNo = itemNoField.getText();//getting the text of the item number from the form
        String itemName = itemNameField.getText();//getting the text of the item name from the form
        String pricePiece = itemPricePiece.getText();//getting the text of the item price per piece from the form
        String priceKg = itemPriceKg.getText();//getting the text of the item price per kg from the form
        int emptyCounter=0;
        int radioCounter=0;

        if (itemNo.isEmpty() || itemName.isEmpty() || pricePiece.isEmpty() || priceKg.isEmpty() )//checking if the field is empty on the form or not
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter data!");//Showing appropriate message in the dialog box if the above condition is true
            emptyCounter++;
        } 
        else//running the else statement if the above condition is false 
        {
            coursework.getdata[0] = this.itemNoField.getText();//getting item no from the form and storing the data in the array as an index 0
            coursework.getdata[1] = this.itemNameField.getText();//getting item no from the form and storing the data in the array as an index 1
            coursework.getdata[4] = this.itemPricePiece.getText();//getting item no from the form and storing the data in the array as an index 4
            coursework.getdata[5] = this.itemPriceKg.getText();//getting item no from the form and storing the data in the array as an index 5
        }
        if (itemCategory.getSelectedItem() == "Select a Category")//checking the condition for the Jcmobo Box 
        {
            JOptionPane.showMessageDialog(rootPane, "Please Select a category!");//Showing appropriate message in the dialog box if the above condition is true
            emptyCounter++;
        } 
        else 
        {
            coursework.getdata[2] = (String) this.itemCategory.getSelectedItem();//getting item no from the form and storing the data in the array as an index 2

        }
        if (radioRegular.isSelected())//exceuting the condtion for the radio button
        {
            coursework.getdata[3] = (String) this.radioRegular.getText();//getting item no from the form and storing the data in the array as an index 3
            radioCounter++;
        } 
        else if (radioLarge.isSelected())//exceuting the condtion for the radio button
        {
            coursework.getdata[3] = (String) this.radioLarge.getText();//getting item no from the form and storing the data in the array as an index 3
            radioCounter++;
        }
        if(radioCounter==0)
        {
            JOptionPane.showMessageDialog(rootPane, "Please select a size!");
        }
        if(emptyCounter==0 && radioCounter>0)
        {
        coursework.postData();//calling the method from the parent class  
        JOptionPane.showMessageDialog(rootPane, "Data has been added!");
        }


    }//GEN-LAST:event_inputAddActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        coursework.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        coursework.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_openActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(rootPane, "Do you want to close?", "Choose", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new InputForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addItems;
    private javax.swing.ButtonGroup buttonReglar;
    private javax.swing.JMenuItem exit;
    private javax.swing.JButton inputAdd;
    private javax.swing.JLabel inputCategory;
    private javax.swing.JLabel inputName;
    private javax.swing.JLabel inputNo;
    private javax.swing.JLabel inputPriceKilos;
    private javax.swing.JLabel inputPricePiece;
    private javax.swing.JSeparator inputSeperator;
    private javax.swing.JLabel inputSize;
    private javax.swing.JComboBox itemCategory;
    private javax.swing.JTextField itemNameField;
    private javax.swing.JTextField itemNoField;
    private javax.swing.JTextField itemPriceKg;
    private javax.swing.JTextField itemPricePiece;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menuLine;
    private javax.swing.JMenuItem open;
    private javax.swing.JRadioButton radioLarge;
    private javax.swing.JRadioButton radioRegular;
    // End of variables declaration//GEN-END:variables
}
